# Generated by Django 3.0.3 on 2020-04-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('subs_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('headlines', models.BooleanField(default=True)),
                ('bussiness', models.BooleanField(default=False)),
                ('entertainment', models.BooleanField(default=False)),
                ('health', models.BooleanField(default=False)),
                ('science', models.BooleanField(default=False)),
                ('technology', models.BooleanField(default=False)),
                ('sports', models.BooleanField(default=False)),
            ],
        ),
    ]
